### ISSUE TITLE
どうやってジャイロスコープを禁止しますか？

### ISSUE THREAD

**Issue by gikeihi** [tattn/VTuberKit#3]
VTuberKitのExampleを試しましたが、ジャイロスコープを使っているため、人間がiPhoneを持って、回転すると、カメラ中に、人間の首も回ってしまいます。

ジャイロスコープを禁止することを可能ですか？

**Comment by tattn** [comment]
良い質問ありがとうございます！

デフォルトでジャイロスコープを無効にしたほうが使いやすくなると思いますので、
v0.2.0で無効にしました。こちらをご利用ください。

en:
Thanks for the good question :)

I think it would be easier to use if the gyroscope was disabled by default,
 so it was disabled in v0.2.0. Please use the version.
